module.exports ={
    products: [
    {   _id: '1',
        name: 'dress',
        sellingPrice:'500',
        actualPrice: '1000',
        brand: 'zara',
        description: 'green floral dress. knee length',
        image: './img/card1.png'
    },
    {   _id: '2',
    name: 'dress',
    sellingPrice:'500',
    actualPrice: '1000',
    brand: 'zara',
    description: 'green floral dress. knee length',
    image: './img/card12.png'
},
{   _id: '3',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card16.png'
},
{   _id: '4',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card21.png'
},
{   _id: '5',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card13.png'
},
{   _id: '6',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card18.png'
},
{   _id: '7',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card2.png'
},
{   _id: '8',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card3.png'
},
{   _id: '9',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card4.png'
},
{   _id: '10',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card5.png'
},
{   _id: '11',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card6.png'
},
{   _id: '12',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card7.png'
},
{   _id: '13',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card8.png'
},
{   _id: '14',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card9.png'
},
{   _id: '15',
name: 'dress',
sellingPrice:'500',
actualPrice: '1000',
brand: 'zara',
description: 'green floral dress. knee length',
image: './img/card10.png'
},

    ],
};